### ISSUE TITLE
发送长文本消息失败 报4114 UNPARSEABLE_RAW_MESSAGE 错误

### ISSUE THREAD

**Issue by DengWang** [leancloud/realtime-SDK-dotNET#107]
发送大概超过800多个字母的文本消息会失败,报4114错误,但是通过reset api可以发送更长的文本消息,消息长度绝对没有超过你们限制5kb,怀疑是本地或者websocket有什么限制导致消息被截断了,造成服务端无法解析.

**Comment by wujun4code** [comment]
能把发送的消息 json 串贴一下么？头一回遇到这种问题，好诡异。好期待这个消息长什么样儿 🚶

**Comment by DengWang** [comment]
消息并没有什么特别的,我贴一个用reset api发的消息,下面这个消息用reset api可以发,但是用客户端sdk就会报错
{"_lctype":-1,"_lctext":"dsdsdsdsdsdsdssdsdsdsdsdsdssdsdsdsdsdsdsdsdsdssdssdsdsadsadsadsadsadasdsadjadasdsadasddsdasdsdasdiuasdasidauidhasdjsahdajksdhaskjahsdkjashdsjkcssdbhfewdeuwi2euehr28ry23987r23eefhwd8f7ry2478hfwrufhw78fgwe78fwegfdwyfgdsiuygsuhvsgfudsgf83g8eyfgdyucgsdvhsbvhdsgvsdiufdbfhdshbcvsiuvhsuisdhfdisufhdsiufhdsufidhsufhferubferiufsuvgefuirhfwiufsdijhsduifhsdiufhfiuwfhsdihsdifsduifhsdiufshdifuhsdufigsfuifyasdasgdahjdgasdgashjdasgdhjagdjhasgsdashjdgasHJdgsahjdgajhdsagdhjsagdahjdgsajhdgajashgdasjhdgasjhdgajhdgady3e83g8y3g4e3yeg238eg2yegyuwge8re872ge82eg278dgydgusdgcsdhjcgfsduhdfgweuyrg2ehsdhjcvsdhufgweuwygfewyucgwuycgwyfwefywvfwygwwgefbwucsducdwuyfgweyugfwiufgweiufgewifyuwegfiwgfwfgwefuygwefuywefusdbvjhxbcvsdhsufgwfwebfsdbsdifgidufgweiufweifudifgwdiufgweiufgwefygwdvbsvbsdsdsdsdsdsdsdssdsdsdsdsdsdssdsdsdsdsdsdsdsdsdssdssdsdsadsadsadsadsadasdsadjadasdsadasddsdasdsdasdiuasdasidauidhasdjsahdajksdhaskjahsdkjashdsjkcssdbhfewdeuwi2euehr28ry23987r23eefhwd8f7ry2478hfwrufhw78fgwe78fwegfdwyfgdsiuygsuhvsgfudsgf83g8eyfgdyucgsdvhsbvhdsgvsdiufdbfhdshbcvsiuvhsuisdhfdisufhdsiufhdsufidhsufhferubferiufsuvgefuirhfwiufsdijhsduifhsdiufhfiuwfhsdihsdifsduifhsdiufshdifuhsdufigsfuifyasdasgdahjdgasdgashjdasgdhjagdjhasgsdashjdgasHJdgsahjdgajhdsagdhjsagdahjdgsajhdgajashgdasjhdgasjhdgajhdgady3e83g8y3g4e3yeg238eg2yegyuwge8re872ge82eg278dgydgusdgcsdhjcgfsduhdfgweuyrg2ehsdhjcvsdhufgweuwygfewyucgwuycgwyfwefywvfwygwwgefbwucsducdwuyfgweyugfwiufgweiufgewifyuwegfiwgfwfgwefuygwefuywefusdbvjhxbcvsdhsufgwfwebfsdbsdifgidufgweiufweifudifgwdiufgweiufgwefygwdvbsvbsdsdsdsdsdsdsdssdsdsdsdsdsdssdsdsdsdsdsdsdsdsdssdssdsdsadsadsadsadsadasdsadjadasdsadasddsdasdsdasdiuasdasidauidhasdjsahdajksdhaskjahsdkjashdsjkcssdbhfewdeuwi2euehr28ry23987r23eefhwd8f7ry2478hfwrufhw78fgwe78fwegfdwyfgdsiuygsuhvsgfudsgf83g8eyfgdyucgsdvhsbvhdsgvsdiufdbfhdshbcvsiuvhsuisdhfdisufhdsiufhdsufidhsufhferubferiufsuvgefuirhfwiufsdijhsduifhsdiufhfiuwfhsdihsdifsduifhsdiufshdifuhsdufigsfuifyasdasgdahjdgasdgashjdasgdhjagdjhasgsdashjdgasHJdgsahjdgajhdsagdhjsagdahjdgsajhdgajashgdasjhdgasjhdgajhdgady3e83g8y3g4e3yeg238eg2yegyuwge8re872ge82eg278dgydgusdgcsdhjcgfsduhdfgweuyrg2ehsdhjcvsdhufgweuwygfewyucgwuycgwyfwefywvfwygwwgefbwucsducdwuyfgweyugfwiufgweiufgewifyuwegfiwgfwfgwefuygwefuywefusdbvjhxbcvsdhsufgwfwebfsdbsdifgidufgweiufweifudifgwdiufgweiufgwefygwdvbsvbsdsdsdsdsdsdsdssdsdsdsdsdsdssdsdsdsdsdsdsdsdsdssdssdsdsadsadsadsadsadasdsadjadasdsadasddsdasdsdasdiuasdasidauidhasdjsahdajksdhaskjahsdkjashdsjkcssdbhfewdeuwi2euehr28ry23987r23eefhwd8f7ry2478hfwrufhw78fgwe78fwegfdwyfgdsiuygsuhvsgfudsgf83g8eyfgdyucgsdvhsbvhdsgvsdiufdbfhdshbcvsiuvhsuisdhfdisufhdsiufhdsufidhsufhferubferiufsuvgefuirhfwiufsdijhsduifhsdiufhfiuwfhsdihsdifsduifhsdiufshdifuhsdufigsfuifyasdasgdahjdgasdgashjdasgdhjagdjhasgsdashjdgasHJdgsahjdgajhdsagdhjsagdahjdgsajhdgajashgdasjhdgasjhdgajhdgady3e83g8y3g4e3yeg238eg2yegyuwge8re872ge82eg278dgydgusdgcsdhjcgfsduhdfgweuyrg2ehsdhjcvsdhufgweuwygfewyucgwuycgwyfwefywvfwygwwgefbwucsducdwuyfgweyugfwiufgweiufgewifyuwegfiwgfwfgwefuygwefuywefusdbvjhxbcvsdhsufgwfwebfsdbsdifgidufgweiufweifudifgwdiufgweiufgwefygwdvbsvbsdsdsdsdsdsdsdssdsdsdsdsdsdssdsdsdsdsdsdsdsdsdssdssdsdsadsadsadsadsadasdsadjadasdsadasddsdasdsdasdiuasdasidauidhasdjsahdajksdhaskjahsdkjashdsjkcssdbhfewdeuwi2euehr28ry23987r23eefhwd8f7ry2478hfwrufhw78fgwe78fwegfdwyfgdsiuygsuhvsgfudsgf83g8eyfgdyucgsdvhsbvhdsgvsdiufdbfhdshbcvsiuvhsuisdhfdisufhdsiufhdsufidhsufhferubferiufsuvgefuirhfwiufsdijhsduifhsdiufhfiuwfhsdihsdifsduifhsdiufshdifuhsdufigsfuifyasdasgdahjdgasdgashjdasgdhjagdjhasgsdashjdgasHJdgsahjdgajhdsagdhjsagdahjdgsajhdgajashgdasjhdgasjhdgajhdgady3e83g8y3g4e3yeg238eg2yegyuwge8re872ge82eg278dgydgusdgcsdhjcgfsduhdfgweuyrg2ehsdhjcvsdhufgweuwygfewyucgwuycgwyfwefywvfwygwwgefbwucsducdwuyfgweyugfwiufgweiufgewifyuwegfiwgfwfgwefuygwefuywefusdbvjhxbcvsdhsufgwfwebfsdbsdifgidufgweiufweifudifgwdiufgweiufgwefygwdvbsvbsdsdsdsdsdsdsdssdsdsdsdsdsdssdsdsdsdsdsdsdsdsdssdssdsdsadsadsadsadsadasdsadjadasdsadasddsdasdsdasdiuasdasidauidhasdjsahdajksdhaskjahsdkjashdsjkcssdbhfewdeuwi2euehr28ry23987r23eefhwd8f7ry2478hfwrufhw78fgwe78fwegfdwyfgdsiuygsuhvsgfudsgf83g8eyfgdyucgsdvhsbvhdsgvsdiufdbfhdshbcvsiuvhsuisdhfdisufhdsiufhdsufidhsufhferubferiufsuvgefuirhfwiufsdijhsduifhsdiufhfiuwfhsdihsdifsduifhsdiufshdifuhsdufigsfuifyasdasgdahjdgasdgashjdasgdhjagdjhasgsdashjdgasHJdgsahjdgajhdsagdhjsagdahjdgsajhdgajashgdasjhdgasjhdgajhdgady3e83g8y3g4e3yeg238eg2yegyuwge8re872ge82eg278dgydgusdgcsdhjcgfsduhdfgweuyrg2ehsdhjcvsdhufgweuwygfewyucgwuycgwyfwefywvfwygwwgefbwucsducdwuyfgweyugfwiufgweiufgewifyuwegfiwgfwfgwefuygwefuywefusdbvjhxbcvsdhsufgwfwebfsdbsdifgidufgweiufweifudifgwdiufgweiufgwefygwdvbsvbs","_lcattrs":{"a":"_lcattrs 是用来存储用户自定义的一些键值对"}}

**Comment by DengWang** [comment]
比上面消息短的只有超过一定长度就会报错,这个长度大概800个字母的样子

**Comment by wujun4code** [comment]
这个就很吊轨了。。我试一下。

**Comment by onerain88** [comment]
这个问题是由于 .Net 这边对于 WebSocket Frame 大小与服务端不一致导致。
目前已在新版本中修复。
