### ISSUE TITLE
unity 初始化的时候，一直报错

### ISSUE THREAD

**Issue by cqusyc** [leancloud/realtime-SDK-dotNET#124]
MethodAccessException: Method `System.TypeExtensions:GetTypeInfo (System.Type)' is inaccessible from method `LeanCloud.AVClient:get_Version ()'
LeanCloud.AVClient..cctor ()
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for LeanCloud.AVClient
LeanCloud.AVInitializeBehaviour.Initialize ()
LeanCloud.AVInitializeBehaviour.Awake ()

**Comment by onerain88** [comment]
请看一下 Unity 运行的 .net 环境版本和导入的库的版本一致吗？
新版的 Unity 支持了 .net 4.x，请导入 4.6 版本的 SDK；否则请使用 3.5 版本

**Comment by cqusyc** [comment]
![image](https://user-images.githubusercontent.com/18522959/50684847-f6c4d180-1051-11e9-9d22-2791012870ee.png)
![image](https://user-images.githubusercontent.com/18522959/50684878-13610980-1052-11e9-9314-fb8192b08c41.png)

**Comment by cqusyc** [comment]
不行,一样的错误。 Unity版本2017.4.17f1

**Comment by onerain88** [comment]
请把 demo 项目打包发上来，我看一下

**Comment by cqusyc** [comment]
我直接项目上做的，我弄个demo试试。。

**Comment by onerain88** [comment]
http://lc-Eohx7L4E.cn-n1.lcfile.com/3e25a133c8b6e078c6bf.zip
这个是我昨天在 .net 4.x 下做的 demo，你可以参考下

**Comment by cqusyc** [comment]
Unity.Compat.dll，Unity.Tasks.dll这两个库跟其他sdk的重了，把leancloud下面的删除就会报错。。
这两个库的路径不能动么

**Comment by onerain88** [comment]
有个 link.xml 配置一下

**Comment by cqusyc** [comment]
没看到文档有写怎么配置的哇

**Comment by onerain88** [comment]
你可以先跑起 demo 来，然后看怎么初始化的，再移植到你的项目中

**Comment by cqusyc** [comment]
移植完了，也有数据了，现在就这个问题了。。

**Comment by onerain88** [comment]
报错贴一下

**Comment by cqusyc** [comment]
没错了，只要把其他路径的Unity.Compat.dll，Unity.Tasks.dll删掉，保留leancloud下的就可以正常跑了。
想问的是怎么可以引用到其他路径下的这两个库？

**Comment by onerain88** [comment]
我猜测和加载顺序有关系，先加载 leancloud，发现依赖库没有，所以报错；反之，则正常

**Comment by cqusyc** [comment]
把整个leancloud放到plugins下面去，库就找不到了。。
