### ISSUE TITLE
第三方登录，支持 UnionID

### ISSUE THREAD

**Issue by nicecui** [leancloud/realtime-SDK-dotNET#126]
API 文档：
之前的登录方式：https://leancloud.cn/docs/rest_api.html#hash-512531360
后来支持了 UnionId：https://leancloud.cn/docs/rest_api.html#hash-1167704513

可参考 JS SDK：https://leancloud.cn/docs/leanstorage_guide-js.html#hash-1165730617

**Comment by onerain88** [comment]
已支持
https://github.com/leancloud/unity-sdk/releases/tag/v20190111.1
