### ISSUE TITLE
存储 SDK，增加匿名登录

### ISSUE THREAD

**Issue by nicecui** [leancloud/realtime-SDK-dotNET#132]
可参考：
https://leancloud.cn/docs/leanstorage_guide-js.html#hash656508733
https://leancloud.cn/docs/rest_api.html#hash1028771764

![image](https://user-images.githubusercontent.com/10130959/51232751-d0345e00-19a2-11e9-905f-64e174009dc7.png)

**Comment by onerain88** [comment]
已支持
