### ISSUE TITLE
onInvited 不会被调用

### ISSUE THREAD

**Issue by nicecui** [leancloud/realtime-SDK-dotNET#150]
测试流程：
1、jerry 使用 JavaScript leanMessage Demo 登录
2、tom 使用 Unity C# 登录
3、jerry 邀请 tom 进入房间
4、tom 的 OnInvited 应该被触发却没有被触发

Tom 相关代码：
```
tom.OnInvited += (sender, args) =>
        {
            Debug.Log("Tom_OnInvited 被调用 -----------");
            var invitedBy = args.InvitedBy;
            var conversationId = args.ConversationId;
        };

```

Tom 相关日志：

sesstion opened.
websocket<={"cmd":"unread","appId":"nWV9ebO1JMUIE5K4gBS1i1MA","convs":[{"cid":"5c6fabecdc0ab2de29ef6b53","unread":1,"mid":"Of9DDwm3Sl6hOl898jefGQ","timestamp":1550822928851,"mentioned":false},{"cid":"5c6fae98dc0ab2de290889b8","unread":1,"mid":"YVhZ_PF2QUKvFP8YkWF1QQ","timestamp":1550823074519,"mentioned":false}],"notifTime":1550823217495,"peerId":"tom","service":2}
websocket<={"op":"joined","initBy":"jerry","appId":"nWV9ebO1JMUIE5K4gBS1i1MA","cmd":"conv","cid":"5c6faf3fdc0ab2de290e1e8e","serverTs":1550823231119,"peerId":"tom","service":2}
websocket<={"op":"members-joined","m":["jerry","tom"],"initBy":"jerry","appId":"nWV9ebO1JMUIE5K4gBS1i1MA","cmd":"conv","cid":"5c6faf3fdc0ab2de290e1e8e","serverTs":1550823231119,"peerId":"tom","service":2}

**Comment by nicecui** [comment]
https://github.com/leancloud/realtime-SDK-dotNET/releases/tag/v20190424.1

**Comment by onerain88** [comment]
被移除会话也有类似的问题，已修复
https://github.com/leancloud/realtime-SDK-dotNET/pull/166

**Comment by onerain88** [comment]
版本发布 https://github.com/leancloud/realtime-SDK-dotNET/releases/tag/v20190424.2
