### ISSUE TITLE
Unity 在Android P系统上会闪退

### ISSUE THREAD

**Issue by mimicryryu** [leancloud/realtime-SDK-dotNET#176]
如果选.net 4.6会闪退，CreateClient的时候对task result得到的client的访问会导致invalid pthread_t xxxx passed to libc 奔溃
选.net3.5不会闪退，但是对client的访问会导致线程卡主

创建Client的代码
```C#
private void CreateClient(string rid, LuaFunction resultCallback = null) {
        try {
            this.KDLLog("CreateClientAsync");
            m_realtime.CreateClientAsync(rid, platformName, deviceUniqueIdentifier).ContinueWith(t => {
                bool isSuccess = !t.IsFaulted && !t.IsCanceled;
                if (isSuccess) {
                    this.KDLLog("CreateClient done");
                    m_client = t.Result;
                    this.KDLLog("m_client = t.Result " + m_client.ClientId);
                    var conf = m_client.CurrentConfiguration;
                    this.KDLLog("m_client.CurrentConfiguration");
                    conf.AutoRead = false; // AutoRead is not required
                    this.KDLLog("conf.AutoRead = false"); //<----到达不了
                    m_client.CurrentConfiguration = conf;
                    this.KDLLog("m_client.CurrentConfiguration = conf");
                    m_client.OnMessageReceived -= OnNewChatMessageReceived;
                    this.KDLLog("m_client.OnMessageReceived -= OnNewChatMessageReceived");
                    m_client.OnMessageReceived += OnNewChatMessageReceived;
                    this.KDLLog("m_client.OnMessageReceived += OnNewChatMessageReceived");
                } else {
                    this.KDLLogErrorFormat("CreateClient failed! IsCanceled:{0} IsFaulted:{1} Exception:{2}", t.IsCanceled, t.IsFaulted, t.Exception);
                }
                EnqueueMainThreadCallback(() => {
                    if (resultCallback != null) {
                        if (resultCallback.IsAlive) {
                            resultCallback.Call(isSuccess);
                            resultCallback.Dispose();
                        } else {
                            this.KDLLogError("resultCallback is not alive!");
                        }
                    }
                });
            });
        } catch (Exception e) {
            this.KDLLogError("CreateClient Error: " + e.ToString());
            if (null != resultCallback) {
                resultCallback.Call(false);
                resultCallback.Dispose();
            }
        }
    }
```

**Comment by mimicryryu** [comment]
targetSdkVersion 26
compileSdkVersion 28

**Comment by onerain88** [comment]
在 ContinueWith() 中的代码是执行在子线程的，我猜测是你的 lua 代码执行在了子线程导致的那个报错。
两种解决方法：
1. 使用 await/async，代码可以更简单，推荐
2. 在 ContinueWith() 的第二个参数，传递「主线程调度」，TaskScheduler.FromCurrentSynchronizationContext()

**Comment by mimicryryu** [comment]
我的luafunction会通过一个EnqueueMainThreadCallback方法排队到主线程调用的，我想应该不是这个问题

**Comment by mimicryryu** [comment]
```C#
    void EnqueueMainThreadCallback(System.Action call) {
        bool enqueued = false;
        while (!enqueued) {
            if (Monitor.TryEnter(m_mainThreadCallbackQueueLock, 50)) {
                m_mainThreadCallbackQueue.Enqueue(call);
                enqueued = true;
                Monitor.Exit(m_mainThreadCallbackQueueLock);
            }
        }
    }

    void LateUpdate() {
        CallMainThreadCallbacks();
    }

    void CallMainThreadCallbacks() {
        if (Monitor.TryEnter(m_mainThreadCallbackQueueLock)) {
            while (m_mainThreadCallbackQueue.Count > 0) {
                m_mainThreadCallbackQueue.Dequeue()();
            }
            Monitor.Exit(m_mainThreadCallbackQueueLock);
        }
    }

```

**Comment by mimicryryu** [comment]
我这边华为的P20pro是9系统，倒是没有问题，一台MIX3（MIUI10.3 Android9）出现了上述问题。我再观察别的设备看看吧

**Comment by onerain88** [comment]
> ```cs
>     void EnqueueMainThreadCallback(System.Action call) {
>         bool enqueued = false;
>         while (!enqueued) {
>             if (Monitor.TryEnter(m_mainThreadCallbackQueueLock, 50)) {
>                 m_mainThreadCallbackQueue.Enqueue(call);
>                 enqueued = true;
>                 Monitor.Exit(m_mainThreadCallbackQueueLock);
>             }
>         }
>     }
> 
>     void LateUpdate() {
>         CallMainThreadCallbacks();
>     }
> 
>     void CallMainThreadCallbacks() {
>         if (Monitor.TryEnter(m_mainThreadCallbackQueueLock)) {
>             while (m_mainThreadCallbackQueue.Count > 0) {
>                 m_mainThreadCallbackQueue.Dequeue()();
>             }
>             Monitor.Exit(m_mainThreadCallbackQueueLock);
>         }
>     }
> ```

这样实现可能死锁吧，如果在回调中会产生要插入主线程队列的情况

**Comment by onerain88** [comment]
如果使用 .net 4.x，建议使用文档中 await/async 的方式

**Comment by mimicryryu** [comment]
线程问题应该是我这边用的bugly插件的问题，在分线程上上报错误时导致闪退了（昨天leancloud服务器有问题

**Comment by isbdnt** [comment]
> 线程问题应该是我这边用的bugly插件的问题，在分线程上上报错误时导致闪退了（昨天leancloud服务器有问题

这个问题后续解决了吗？但是bugly那个调用看起来像是hook，如果是hook的话，就不是bugly的问题了？

**Comment by onerain88** [comment]
如果是新项目，可以了解一下新版 [SDK](https://github.com/leancloud/csharp-sdk)，基于 .net Standard 2.0 开发的

**Comment by isbdnt** [comment]
> 如果是新项目，可以了解一下新版 [SDK](https://github.com/leancloud/csharp-sdk)，基于 .net Standard 2.0 开发的

我这边是调用Unity的GPU Instancing的过程中，发生了闪退，跟LeanCloud好像没啥关系，这个tgkill闪退非常诡异，几乎所有的奇奇怪怪的闪退最终都是由这个API导致的，不知道是Unity底层线程调度的bug还是bugly的问题

08-25 18:31:22.002 10371 10516 E CRASH   :      #00  pc 0004b8fc  /system/lib/libc.so (tgkill+12)
08-25 18:31:22.002 10371 10516 E CRASH   :      #01  pc 0001a4e3  /system/lib/libc.so (abort+54)
08-25 18:31:22.002 10371 10516 E CRASH   :      #02  pc 0001eab9  /system/lib/libc.so (__libc_fatal+24)
08-25 18:31:22.002 10371 10516 E CRASH   :      #03  pc 00048efd  /system/lib/libc.so (__pthread_internal_find(long)+80)
08-25 18:31:22.002 10371 10516 E CRASH   :      #04  pc 00048e01  /system/lib/libc.so (pthread_gettid_np+2)
08-25 18:31:22.002 10371 10516 E CRASH   :      #05  pc 00049207  /system/lib/libc.so (pthread_kill+18)
08-25 18:31:22.002 10371 10516 E CRASH   :      #06  pc 00005889  /data/app/com.sofunny.chickendinnerfirst-cnDrfzYWbjeMCIiPjJrcTg==/lib/arm/libBugly.so
08-25 18:31:22.002 10371 10516 E CRASH   :      #07  pc 00002363  /system/bin/app_process32
08-25 18:31:22.002 10371 10516 E CRASH   :      #08  pc 00018b64  /system/lib/libc.so
08-25 18:31:22.002 10371 10516 E CRASH   :      #09  pc 0124c854  /data/app/com.sofunny.chickendinnerfirst-cnDrfzYWbjeMCIiPjJrcTg==/lib/arm/libunity.so (UniformCacheGLES::Submit(unsigned int, dynamic_array<GpuProgramParameters::ValueParameter, 0u> const&, dynamic_array<int, 0u> const&) const+196)
08-25 18:31:22.002 10371 10516 E CRASH   :      #10  pc 012394a4  /data/app/com.sofunny.chickendinnerfirst-cnDrfzYWbjeMCIiPjJrcTg==/lib/arm/libunity.so (GlslGpuProgramGLES::Bind(unsigned int, GpuProgramParameters const&, unsigned int)+184)
08-25 18:31:22.002 10371 10516 E CRASH   :      #11  pc 012304fc  /data/app/com.sofunny.chickendinnerfirst-cnDrfzYWbjeMCIiPjJrcTg==/lib/arm/libunity.so (GfxDeviceGLES::BeforeDrawCall()+128)
08-25 18:31:22.002 10371 10516 E CRASH   :      #12  pc 0123130c  /data/app/com.sofunny.chickendinnerfirst-cnDrfzYWbjeMCIiPjJrcTg==/lib/arm/libunity.so (GfxDeviceGLES::DrawBuffers(GfxBuffer*, int, VertexStreamSource const*, int, DrawBuffersRange const*, int, VertexDeclaration*)+176)
08-25 18:31:22.002 10371 10516 E CRASH   :      #13  pc 00611e64  /data/app/com.sofunny.chickendinnerfirst-cnDrfzYWbjeMCIiPjJrcTg==/lib/arm/libunity.so (GfxDeviceWorker::RunCommand(ThreadedStreamBuffer&)+15580)
08-25 18:31:22.002 10371 10516 E CRASH   :      #14  pc 006158d4  /data/app/com.sofunny.chickendinnerfirst-cnDrfzYWbjeMCIiPjJrcTg==/lib/arm/libunity.so (GfxDeviceWorker::RunExt(ThreadedStreamBuffer&)+68)
08-25 18:31:22.002 10371 10516 E CRASH   :      #15  pc 00615864  /data/app/com.sofunny.chickendinnerfirst-cnDrfzYWbjeMCIiPjJrcTg==/lib/arm/libunity.so (GfxDeviceWorker::Run()+132)
08-25 18:31:22.002 10371 10516 E CRASH   :      #16  pc 0060dea0  /data/app/com.sofunny.chickendinnerfirst-cnDrfzYWbjeMCIiPjJrcTg==/lib/arm/libunity.so (GfxDeviceWorker::RunGfxDeviceWorker(void*)+4)
08-25 18:31:22.002 10371 10516 E CRASH   :      #17  pc 00acacd0  /data/app/com.sofunny.chickendinnerfirst-cnDrfzYWbjeMCIiPjJrcTg==/lib/arm/libunity.so (Thread::RunThreadWrapper(void*)+696)
08-25 18:31:22.002 10371 10516 E CRASH   :      #18  pc 00048c1f  /system/lib/libc.so (__pthread_start(void*)+22)
08-25 18:31:22.002 10371 10516 E CRASH   :      #19  pc 0001b09f  /system/lib/libc.so (__start_thread+32)
