### ISSUE TITLE
登出报错,invalid JSON-format

### ISSUE THREAD

**Issue by 777777716** [leancloud/realtime-SDK-dotNET#35]
在Unity Editor,先登录，成功后，登出
>received websocket data with a invalid JSON-format.
UnityEngine.Debug:Log(Object)
LeanCloud.Realtime.AVRealtime:PrintLog(String)
LeanCloud.Realtime.AVRealtime:WebSocketClient_OnMessage(String)
LeanCloud.Realtime.Internal.DefaultWebSocketClient:OnWebSokectMessage(Object, MessageEventArgs)
WebSocketSharp.Ext:Emit(EventHandler`1, Object, MessageEventArgs)
WebSocketSharp.WebSocket:messagec(MessageEventArgs)
WebSocketSharp.WebSocket:message()
WebSocketSharp.<>c__DisplayClass175_0:<startReceiving>b__1(WebSocketFrame)
WebSocketSharp.<>c__DisplayClass83_0:<ReadFrameAsync>b__3(WebSocketFrame)
WebSocketSharp.<>c__DisplayClass77_0:<readPayloadDataAsync>b__0(Byte[])
WebSocketSharp.<>c__DisplayClass55_0:<ReadBytesAsync>b__0(IAsyncResult)

**Comment by wujun4code** [comment]
已修复，客户端不再强制检测 json 格式了。
