### ISSUE TITLE
按照错误码文档 1006 SDK 会自动重连,但是现在只有0才会自动重连

### ISSUE THREAD

**Issue by DengWang** [leancloud/realtime-SDK-dotNET#48]

**Comment by wujun4code** [comment]
能贴一下你的本地日志么？

**Comment by DengWang** [comment]
![image](https://user-images.githubusercontent.com/2217844/30311591-a4c6c4a8-975b-11e7-857d-35cd3a2f444b.png) 用这个东西限制网络 一段时间之后就出现
websocket closed with code is 1006,reason is An exception has occurred while receiving. and detail is 
之后恢复心跳包一直再发,但是没有重连了,看了下源代码只有0才会自动重连
![image](https://user-images.githubusercontent.com/2217844/30311707-2b27df96-975c-11e7-9d02-8ad17d4bf5ee.png)
