### ISSUE TITLE
[feat]将 Unread 和 Unreceived 状态分离

### ISSUE THREAD

**Issue by wujun4code** [leancloud/realtime-SDK-dotNET#85]
##  Quick look

conversation 开放两个属性：

Unreceived 和 Unread

第一是属性是：
### ~Unreceived~

```cs
        public class UnreceivedState
        {
            /// <summary>
            /// unreceived count
            /// </summary>
            public int Count { get; internal set; }


            /// <summary>
            /// last unreceived message
            /// </summary>
            public IAVIMMessage LastMessage { get; internal set; }

            /// <summary>
            /// last sync timestamp
            /// </summary>
            public float SyncdAt { get; internal set; }
        }
```

###  Unreceived 使用规则

在  OfflineMessageStrategy = AVRealtime.OfflineMessageStrategy.**UnreadNotice** 下，也就是 v2 协议下，因为**不区分接收回执和已读回执**，所以在这种策略下，需要开发者在拉取一个对话之后，去读取这个对话的 Unreceived 属性，通过该属性获得**离线期间产生的消息数量，最新的一条离线消息，以及上一次你离线的时间戳**，用来做 UI 展示，实例代码如下：

```cs
client.GetConversationAsync("axadsadq3edsaas").ContinueWith(t =>
{
    var conversation = t.Result;
    var offlineMessageCount = conversation.Unreceived.Count;
    var lastOfflineMessage = conversation.Unreceived.LastMessage;
    var lastLeftTimestamp = conversation.Unreceived.SyncdAt;
});
```

第二个属性是：
### Unread 

```cs
        public class UnreadState
        {
            /// <summary>
            /// unread count
            /// </summary>
            public int Count { get; internal set; }
            /// <summary>
            /// last unread message
            /// </summary>
            public IAVIMMessage LastMessage { get; internal set; }

            /// <summary>
            /// last sync timestamp
            /// </summary>
            public float SyncdAt { get; internal set; }
        }
```

在  OfflineMessageStrategy = AVRealtime.OfflineMessageStrategy.**UnreadAck** 下，也就是 v3 协议下，因为**接收回执和已读回执的 ack 是分别维护和发送的**，因此开发者在实现离线消息（也就是未接收消息）和未读消息，需要两个属性分别表示，因为在某些应用场景下，**已接收并不意味着一定是已读**，代码实例如下：

```cs
client.GetConversationAsync("axadsadq3edsaas").ContinueWith(t =>
{
    var conversation = t.Result;

    var unreadMessageCount  =  conversation.Unread.Count;
    var lastReadMessage = conversation.Unread.LastMessage;
    var lastReadAt = conversation.Unread.SyncdAt;
});


```

**Comment by wujun4code** [comment]
经过讨论，Unreceived 不具备通用性，不予支持。

**Comment by wujun4code** [comment]
## v.3 协议

1. 登录之后 Unread 的状态显示的最后一条未读的消息和时间戳以及同步时间

2. 收到新消息之后，也要同步更新 Unread 里面对应的数据，把里面的数据更新一下

3. 收到新消息之后，也要同步更新 Received 里面对应的数据

4. 调用 QueryMessageAsync 的时候需要刷新 receive ack 不能发送 read ack

## v.2 协议

1. 登录之后 Unread 的状态显示的最后一条未读的消息和时间戳以及同步时间

2. 收到新消息之后，也要同步更新 Unread 里面对应的数据，把里面的数据更新一下

3. 调用 QueryMessageAsync 的时候需要刷新 receive ack

**Comment by wujun4code** [comment]
#86

**Comment by wujun4code** [comment]
## 收到新消息 Unread 属性怎么维护？

**Comment by onerain88** [comment]
我目前想到的机制：sdk 首先监听 OnMessageReceived，如果在线收到消息，则修改此对话下的 Unread 属性。

**Comment by wujun4code** [comment]
## 已读状态本地不好维护

假设一个对话，是全新创建的，并没有离线消息，此时他的 Unread 是 null，然后在线收到了 50 条消息，他调用了 ReadAysnc 的传输了第 某一条消息的 ID，但是因为**当前 SDK 并没有在内存里面记录当前对话消息列表**，因此根本无法计算出还剩下多少条是未读的。

跟尴尬 😢
